# Numpy 
NumPy is a Python library used for working with arrays.\n
It also has functions for working in domain of linear algebra, fourier transform, and matrice

# Create a NumPy ndarray Object

In [1]:
import numpy as np
arr=np.array([3,6,9])
print(arr)
print(type(arr))

[3 6 9]
<class 'numpy.ndarray'>


# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [2]:
arr=np.array(3)
print(arr)

3


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [3]:
arr=np.array([3,6,9])
print(arr)

[3 6 9]


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

In [4]:
arr=np.array([[3,6,9],[3,6,9]])
print(arr)

[[3 6 9]
 [3 6 9]]


# Array of zeros
NumPy lets you create an array of all zeros using the np.zeros() method

In [5]:
arr=np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


# Array of ones
Create an array of all 1s using the np.ones() method:

In [6]:
arr=np.ones(9)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Random numbers in ndarrays
Create ndarrays is np.random.rand() method. It creates an array of a given shape with random values from [0,1):

In [7]:
arr=np.random.rand(3,2)  # 3 Rows & 2 Colomns
print(arr)

[[0.00696553 0.44362705]
 [0.14154635 0.39258997]
 [0.51726128 0.10882286]]


# Array of your choice
Create an array filled with any given value using the np.full() method. Just pass in the shape of the desired array and the value you want:

In [8]:
arr=np.full((2,2),3)
print(arr)

[[3 3]
 [3 3]]


# Arange Array

In [9]:
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
arr=np.arange(2,12,3)
print(arr)

[ 2  5  8 11]


In [11]:
arr=np.arange(25)
arr=arr.reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
